#pragma once

#define COMBOS

// #define USE_MATRIX_I2C

#define MASTER_LEFT
// #define MASTER_RIGHT
// #define EE_HANDS

#define USE_SERIAL_PD2

#define PERMISSIVE_HOLD
#define TAPPING_TERM 200

#define COMBO_TERM 20
#define COMBO_TERM_PER_COMBO
#define EXTRA_SHORT_COMBOS
#define COMBO_MUST_TAP_PER_COMBO
#define COMBO_SHOULD_TRIGGER
// #define COMBO_STRICT_TIMER

#define TAPPING_TOGGLE 2

#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"

// #define SPLIT_TRANSPORT_MIRROR
// #define SPLIT_LAYER_STATE_ENABLE
#define RGB_MATRIX_KEYPRESSES
#define RGB_DISABLE_WHEN_USB_SUSPENDED
/* #define RGB_MATRIX_FRAMEBUFFER_EFFECTS */
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 140
#define RGB_MATRIX_HUE_STEP 8
#define RGB_MATRIX_SAT_STEP 8
#define RGB_MATRIX_VAL_STEP 8
#define RGB_MATRIX_SPD_STEP 10

// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
// #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
// #define ENABLE_RGB_MATRIX_MULTISPLASH
// #define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

/* #define ENABLE_RGB_MATRIX_ALPHAS_MODS */
/* #define ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN */
/* #define ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT */
/* #define ENABLE_RGB_MATRIX_BREATHING */
/* #define ENABLE_RGB_MATRIX_BAND_SAT */
/* #define ENABLE_RGB_MATRIX_BAND_VAL */
/* #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT */
/* #define ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL */
/* #define ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT */
/* #define ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL */
/* #define ENABLE_RGB_MATRIX_CYCLE_ALL */
/* #define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT */
/* #define ENABLE_RGB_MATRIX_CYCLE_UP_DOWN */
/* #define ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON */
/* #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN */
/* #define ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL */
/* #define ENABLE_RGB_MATRIX_CYCLE_PINWHEEL */
/* #define ENABLE_RGB_MATRIX_CYCLE_SPIRAL */
/* #define ENABLE_RGB_MATRIX_DUAL_BEACON */
/* #define ENABLE_RGB_MATRIX_RAINBOW_BEACON */
/* #define ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS */
/* #define ENABLE_RGB_MATRIX_RAINDROPS */
/* #define ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS */
/* #define ENABLE_RGB_MATRIX_HUE_BREATHING */
/* #define ENABLE_RGB_MATRIX_HUE_PENDULUM */
/* #define ENABLE_RGB_MATRIX_HUE_WAVE */
/* #define ENABLE_RGB_MATRIX_TYPING_HEATMAP */
/* #define ENABLE_RGB_MATRIX_DIGITAL_RAIN */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS */
/* #define ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS */
/* #define ENABLE_RGB_MATRIX_SPLASH */
/* #define ENABLE_RGB_MATRIX_SOLID_SPLASH */

#define FORCE_NKRO

#undef PRODUCT
#define PRODUCT "crkbd"
