#pragma once

//#define USE_MATRIX_I2C

#define MASTER_LEFT
// #define MASTER_RIGHT
// #define EE_HANDS

#define USE_SERIAL_PD2

/* #define TAPPING_FORCE_HOLD */
#define IGNORE_MOD_TAP_INTERRUPT
/* #define PERMISSIVE_HOLD */
#define TAPPING_TERM 200

#define TAPPING_TOGGLE 2

#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"

#define RGB_MATRIX_KEYPRESSES
#define RGB_DISABLE_WHEN_USB_SUSPENDED
/* #define RGB_MATRIX_FRAMEBUFFER_EFFECTS */
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define RGB_MATRIX_HUE_STEP 8
#define RGB_MATRIX_SAT_STEP 8
#define RGB_MATRIX_VAL_STEP 8
#define RGB_MATRIX_SPD_STEP 10

#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_GRADIENT_UP_DOWN
#define DISABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
#define DISABLE_RGB_MATRIX_BREATHING
#define DISABLE_RGB_MATRIX_BAND_SAT
#define DISABLE_RGB_MATRIX_BAND_VAL
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
#define DISABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_SAT
#define DISABLE_RGB_MATRIX_BAND_SPIRAL_VAL
#define DISABLE_RGB_MATRIX_CYCLE_ALL
#define DISABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define DISABLE_RGB_MATRIX_CYCLE_UP_DOWN
#define DISABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN
#define DISABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
#define DISABLE_RGB_MATRIX_CYCLE_PINWHEEL
#define DISABLE_RGB_MATRIX_CYCLE_SPIRAL
#define DISABLE_RGB_MATRIX_DUAL_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_BEACON
#define DISABLE_RGB_MATRIX_RAINBOW_PINWHEELS
#define DISABLE_RGB_MATRIX_RAINDROPS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_HUE_BREATHING
#define DISABLE_RGB_MATRIX_HUE_PENDULUM
#define DISABLE_RGB_MATRIX_HUE_WAVE
#define DISABLE_RGB_MATRIX_TYPING_HEATMAP
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
/* #define DISABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE */
/* #define DISABLE_RGB_MATRIX_SOLID_REACTIVE */
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
/* #define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE */
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
/* #define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS */
#define DISABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
/* #define DISABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS */
#define DISABLE_RGB_MATRIX_SPLASH
/* #define DISABLE_RGB_MATRIX_MULTISPLASH */
#define DISABLE_RGB_MATRIX_SOLID_SPLASH
/* #define DISABLE_RGB_MATRIX_SOLID_MULTISPLASH */

#undef PRODUCT
#define PRODUCT crkbd
